version: "3"
services:
  zookeeper:
    # image: wurstmeister/zookeeper:latest
    image: zookeeper:latest
    restart: always
    ports:
      - "2181:2181"
  kafka-cluster:
    image: wurstmeister/kafka:latest
    restart: always
    depends_on: 
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_PORT: 9092
      KAFKA_ADVERTISED_HOST_NAME: kafka-cluster
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "create-user:1:1, find-all-user:1:1" #testing topics
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  app:
    build: ../app/Dockerfile
    image: app
    restart: always
    depends_on: 
      - kafka-cluster
    ports: 
      - '8000:8000'
    environment: 
      BROKER: kafka-cluster:9092
      SERVER_PORT: 8000
  user-engine:
    build: ../user-engine/Dockerfile
    image: user-engine
    restart: always
    depends_on: 
      - kafka-cluster
    environment:
      BROKER: kafka-cluster:9092
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
  authentication-engine:
    build: ../authentication-engine/Dockerfile
    image: authentication-engine
    restart: always
    depends_on: 
      - kafka-cluster
    environment:
      BROKER: kafka-cluster:9092
  encryption-engine:
    build: ../encryption-engine/Dockerfile
    image: encryption-engine
    restart: always
    depends_on: 
      - kafka-cluster
    environment: 
      BROKER: kafka-cluster:9092
  product-engine:
    build: ../product-engine/Dockerfile
    image: product-engine
    restart: always
    depends_on: 
      - kafka-cluster
    environment: 
      BROKER: kafka-cluster:9092
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
  postgres:
      image: postgres:latest
      restart: always
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=docker
      ports:
        - '5432:5432'
      volumes: 
        # - ./postgres-data:/var/lib/postgresql/data
        # copy the sql script to create databases
        - ./create_databases.sql:/docker-entrypoint-initdb.d/create_databases.sql